//! SeaORM Entity. Generated by sea-orm-codegen 0.5.0

use async_graphql::Enum;
use sea_orm::{entity::prelude::*, ActiveValue, IntoActiveValue, Set};

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Enum, Copy, Eq)]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "transaction_type_enum"
)]
pub enum TransactionTypeEnum {
    #[sea_orm(string_value = "EXPENSE")]
    Expense,
    #[sea_orm(string_value = "INCOME")]
    Income,
}

impl IntoActiveValue<Self> for TransactionTypeEnum {
    fn into_active_value(self) -> ActiveValue<Self> {
        Set(self)
    }
}

#[derive(Debug, Clone, PartialEq, EnumIter, DeriveActiveEnum, Enum, Copy, Eq)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "provider_enum")]
pub enum ProviderEnum {
    #[sea_orm(string_value = "APPLE")]
    Apple,
    #[sea_orm(string_value = "GOOGLE")]
    Google,
    #[sea_orm(string_value = "LOCAL")]
    Local,
}
